### ISSUE TITLE
Debugging the Custom Plugins

### ISSUE THREAD

**Issue by jeethesh-pai** [NVIDIA-AI-IOT/tensorrt_plugin_generator#2]
Thank you so much for this wonderful repository. This helped to create custom plugin library in the most efficient way. Is there a way to test the enqueue function because there seems to be some bugs associated with the kernel calculations?

Thanks in advance 
Jeethesh

**Comment by zerollzeng** [comment]
Do you mean you met error during enqueue? should be caused by the kernel implementation?

**Comment by zerollzeng** [comment]
I would suggest to debug it using cuda-gdb

**Comment by jeethesh-pai** [comment]
Thank you @zerollzeng, 
It is due to kernel implementation. I was able to debug using cuda-gdb but since Enqueue function inputs are pointers ```void const *const *inputs, void *const *outputs```. I am not able to figure out how the array is passed to enqeue function. What the size of array is?

**Comment by zerollzeng** [comment]
> I am not able to figure out how the array is passed to enqeue function. What the size of array is?

It's the input of you plugin, so it depends on how do you configure it.

**Comment by jeethesh-pai** [comment]
Hi @zerollzeng 

if my input of my Plugin is something like this 
```
MSDeformAttentionPlugin:
  attributes:
    im2col_step:
      datatype: int32
  inputs:
    tpg_input_0: # value
      shape: -1x18259x8x32
    tpg_input_1: # value_spatial_shapes
      shape: 4x2
    tpg_input_2: # value_level_start_index
      shape: 4
    tpg_input_3: # sampling_locations
      shape: -1x-1x8x4x4x2
    tpg_input_4: # attention_weights
      shape: -1x-1x8x4x4
  outputs:
    tpg_output_0:
      shape: -1x-1x256
  plugin_type: IPluginV2DynamicExt
  support_format_combination:
    - "float32+int32+int32+float32+float32+float32"
```

will the inputs be passed with the same style as passed here or will they be flattened?

e.g. should I access the tpg_input_1 like 

```
const float* var1 = reinterpret_cast<const float *>(inputs[0]);
and then access individual elements like var1[0][18256][31] ?
```

Thanks
